### ISSUE TITLE
Determine whether installing required packages or not

### ISSUE THREAD

**Issue by ikegami-yukino** [himkt/tiny_tokenizer#14]
Hi,
I like this sentence tokenizer.
But, I use this package as only sentence tokenizer.
Therefore I do not like to install required packages ['natto-py', 'kytea', 'sentencepiece']
I would like to determine `install_requires` interactively.

For example, how about adding the following codes to `setup.py`?
```python
from setuptools import find_packages
from setuptools import setup

install_requires = ['natto-py', 'kytea', 'sentencepiece']
if input('> Do you use this package as only sentence tokenizer? [Y/n]').upper() == 'Y':
    install_requires = []

setup(name='tiny_tokenizer',
      version='1.3.0',
      description='Tiny Word/Sentence Tokenizer',
      author='himkt',
      author_email='himkt@klis.tsukuba.ac.jp',
      install_requires=install_requires,
      url='https://github.com/himkt/tiny_tokenizer',
      packages=find_packages())
```

**Comment by himkt** [comment]
Thanks for the feedback!
As your opinion makes sense, I introduced the environment variable to disable word tokenizers.

Could you please take a look at #15 and give me some comments if you have? 🙇

**Comment by himkt** [comment]
Solved. Thanks for the issue. :+1:
